### ISSUE TITLE
Problem with tracepath

### ISSUE THREAD

**Issue by standa4** [sookyp/honeyd-python#2]
Hello,

when i try to trace the path to honeypot with use of tracapath command the honeyd returns the following error:
2017-06-05 11:57:22,526 Exception: Cannot send reply packet: send: Message too long
Traceback (most recent call last):
  File "/opt/honeyd-python/honeyd/core/dispatcher.py", line 256, in icmp_reply
    self.pcapy_object.sendpacket(reply_eth.get_packet())
PcapError: send: Message too long

Can you look at it what could be the problem. 
Thank you.

**Comment by sookyp** [comment]
Hi @standa4,

it seems that packets were not truncated properly and this resulted in replies larger than ``pcapy`` allows. Should be fixed in the 10e42dd commit. I'd like to mention that for ``tracepath`` to terminate the UDP ports should be configured to ``filtered`` state, as this behavior replies with the expected ICMP error message.

**Comment by standa4** [comment]
Thank you for your response.
The problem was fixed.
